"""
traffic_gen/gen_mgen.py

Render a TrafficScenario (traffic_model.py) into an MGEN script (.mgn).

MGEN is the primary sender: one tool, scheduled multi-flow, per-flow TOS, and
both PERIODIC (CBR) and POISSON patterns -- a direct 1:1 translation of the
model, no reinterpretation. The renderer never invents a TOS: it takes it from
FlowSpec.tos (dscp_to_tos), which is the single place the DS-field byte is
computed, so a mark can't drift from the classifier here.

MGEN line grammar emitted (see MGEN User's Guide, NRL):

    <t> ON <flowId> UDP DST <ip>/<port> <PATTERN> [<params>] TOS <hex>
    <t> OFF <flowId>

  - PERIODIC [rate size]  : rate = messages/second, size = payload bytes.
  - POISSON  [rate size]  : rate = average messages/second.
  - TOS takes the full 8-bit DS byte (DSCP<<2), matching what the N6
    interceptor reads back at IP byte 1 (n6_interceptor._extract_dscp).

Usage:
    python -m traffic_gen.gen_mgen --dst 10.45.0.1 --base-port 5000 \
        --duration 600 --out scenarios/eva_dump.mgn

The DST is the Earth-side sink address the UE routes to (through the UPF / N6);
the trace we care about is captured at N6 regardless of what the sink does with
the packets, so the sink can be a throwaway MGEN receiver or /dev/null-ish.
"""

from __future__ import annotations

import argparse
from typing import List

from .traffic_model import (
    TrafficScenario, reference_scenario, smoke_scenario, trace_scenario, Pattern,
)


def render_mgen(scenario: TrafficScenario, dst_ip: str, base_port: int,
                base_src_port: int = 6000) -> str:
    """Return the full .mgn script text for `scenario`.

    Each flow gets a distinct MGEN flow id (1..N), a distinct UDP dest port
    (base_port + i), AND a distinct source port (base_src_port + i).

    The distinct SRC port is REQUIRED, not cosmetic: MGEN shares one transmit
    socket among flows to the same destination, and TOS is a socket-level
    option (setsockopt IP_TOS), so without per-flow source ports the LAST
    flow's TOS silently overwrites every other flow's -- verified on the
    testbed (all four classes came out with a single DS field). A distinct SRC
    port forces a separate socket per flow, so each flow keeps its own mark.
    """
    lines: List[str] = []
    lines.append("# LunaBridge emulated uplink -- generated by gen_mgen.py")
    lines.append("# DO NOT EDIT BY HAND: edit traffic_gen/traffic_model.py and re-render.")
    lines.append(f"# scenario duration = {scenario.duration_s:.0f}s, "
                 f"peak offered = {scenario.peak_offered_bps()/1e6:.2f} Mbps "
                 f"(relay = 10.00 Mbps)")
    lines.append("#")

    for i, f in enumerate(scenario.flows, start=1):
        port = base_port + i
        src_port = base_src_port + i
        start = max(0.0, f.start_s)
        stop = scenario.duration_s if f.stop_s is None else min(f.stop_s, scenario.duration_s)
        if start >= scenario.duration_s:
            continue  # flow starts after the run ends -- skip it entirely

        # MGEN wants integer-ish rates; keep one decimal for POISSON's small
        # averages, but MGEN accepts floats so we pass them through faithfully.
        rate = f.msgs_per_sec
        rate_str = f"{rate:g}"

        lines.append(f"# flow {i}: {f.name} [{f.cls.value}] -- {f.rationale}")
        lines.append(
            f"{start:.3f} ON {i} UDP SRC {src_port} DST {dst_ip}/{port} "
            f"{f.pattern.value} [{rate_str} {f.msg_size}] "
            f"TOS 0x{f.tos:02x}"
        )
        # Always emit an OFF, at the flow's stop time or the scenario end,
        # whichever is first. This makes the script SELF-TERMINATING: MGEN with
        # only run-length flows never exits on its own, which hangs any
        # launcher. Bounding every flow at scenario.duration_s guarantees mgen
        # returns cleanly at the end of the run.
        lines.append(f"{stop:.3f} OFF {i}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Render a LunaBridge MGEN script.")
    ap.add_argument("--dst", required=True,
                    help="Earth-side sink IP the UE routes to (through N6).")
    ap.add_argument("--base-port", type=int, default=5000,
                    help="First UDP dest port; flow i uses base-port+i.")
    ap.add_argument("--duration", type=float, default=600.0,
                    help="Scenario wall-clock duration in seconds.")
    ap.add_argument("--out", default="-",
                    help="Output .mgn path, or '-' for stdout.")
    ap.add_argument("--smoke", action="store_true",
                    help="Render the short all-classes smoke scenario instead "
                         "of the reference mission profile.")
    ap.add_argument("--trace", action="store_true",
                    help="Render the bounded class-mix trace scenario (for the "
                         "trace->scheduler label-respect run).")
    args = ap.parse_args()

    if args.smoke:
        scenario = smoke_scenario(duration_s=args.duration)
    elif args.trace:
        scenario = trace_scenario(duration_s=args.duration)
    else:
        scenario = reference_scenario(duration_s=args.duration)
    text = render_mgen(scenario, dst_ip=args.dst, base_port=args.base_port)

    if args.out == "-":
        print(text, end="")
    else:
        with open(args.out, "w") as fh:
            fh.write(text)
        peak = scenario.peak_offered_bps() / 1e6
        print(f"wrote {args.out}: {len(scenario.flows)} flows, "
              f"{args.duration:.0f}s, peak {peak:.2f} Mbps")


if __name__ == "__main__":
    main()
